# This rule is not used by the project demo-operators itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over workshop.workshop.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: demo-operators
    app.kubernetes.io/managed-by: kustomize
  name: paychex-admin-role
rules:
- apiGroups:
  - workshop.workshop.io
  resources:
  - paychexes
  verbs:
  - '*'
- apiGroups:
  - workshop.workshop.io
  resources:
  - paychexes/status
  verbs:
  - get
